allow-lan: true
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  nameserver:
    - 223.5.5.5
    - 223.6.6.6
    - 1.2.4.8
    - 1.1.1.1
    - 114.114.114.114
  fallback:
    - https://101.101.101.101/dns-query
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  nameserver-policy: {}
  fake-ip-filter:
    - "*.lan"
    - "*.local"
    - +.msftncsi.com
    - +.msftconnecttest.com
    - edge.microsoft.com
    - edge-http.microsoft.com
external-controller: 127.0.0.1:9097
external-controller-cors:
  allow-origins:
    - "*"
  allow-private-network: true
log-level: info
mixed-port: 7892
mode: rule
tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - 198.18.0.2:53